// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mbszeoihdmomcbokhxwh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ic3plb2loZG1vbWNib2toeHdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMTQxODgsImV4cCI6MjA2NzU5MDE4OH0.AMqQ3MFW3cROPr_qPCc7L520d8-jdACGBdqT6mtnbIA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});